// This file is auto-generated by Interflex.
// Do not edit this file.

import { InterflexKey } from "interflex";
import {
  generateInterflexClient,
  generateInterflexUtils,
  type InterflexClientOptions,
} from "interflex/next";
import translations from "./translations.json";

type I18nKey = InterflexKey<typeof translations>;

type I18nVariables = {
  title: { name: string };
  showDate: { date: Date };
};

type I18nLanguage = keyof typeof translations;

const DEFAULT_LOCALE = "en";

const options: InterflexClientOptions<I18nLanguage> = {
  defaultLocale: DEFAULT_LOCALE,
};

const { useI18n, withInterflex, InterflexProvider } = generateInterflexClient<
  I18nKey,
  I18nVariables,
  I18nLanguage
>(translations, options);

const { i18n } = generateInterflexUtils<I18nKey, I18nVariables, I18nLanguage>(
  translations,
  options
);

export const LOCALES = Object.keys(translations) as I18nLanguage[];

export {
  useI18n,
  withInterflex,
  InterflexProvider,
  i18n,
  DEFAULT_LOCALE,
  type I18nKey,
  type I18nVariables,
  type I18nLanguage,
};
