// This file is auto-generated by Interflex.
// Do not edit this file.

import { InterflexKey } from "interflex";
import { generateInterflexClient } from "interflex/react";
import translations from "./translations.json";

type I18nKey = InterflexKey<typeof translations>;

type I18nVariables = {
  "h.hello": { name: string };
  "h.bye": { name: string };
  "test.1": { age: number, date: Date };
  "footer.left": { num: number }
};

type I18nLanguage = keyof typeof translations;

const { useI18n } = generateInterflexClient<I18nKey, I18nVariables, I18nLanguage>(translations);

export { useI18n, type I18nKey, type I18nVariables, type I18nLanguage };
