// This file is auto-generated by Interflex.
// Do not edit this file.

import { InterflexKey } from "interflex";
import { generateInterflexClient } from "interflex/react";
import translations from "./translations.json";

type I18nKey = InterflexKey<typeof translations>;

type Variables = {
  "h.hello": { name: string };
  "h.bye": { name: string };
  "test.1": { age: number, date: Date };
  "test.2": {};
  "footer.right": {};
  "footer.left": { num: number };
  "footer.middle": {}
};

type Languages = keyof typeof translations;

const { useI18n } = generateInterflexClient<I18nKey, Variables, Languages>(translations);

export { useI18n };
